package nextpos.app.nextpos.model.enums;

public enum VerificationType {
    USER_REGISTRATION,
    PASSWORD_RESET,
    COMPANY_VERIFICATION,
    WAREHOUSE_VERIFICATION,
    EMAIL_CHANGE_CONFIRMATION,
    EMAIL_OTP_LOGIN,
    TWO_FACTOR_AUTH,
    TRANSACTION_CONFIRMATION,
    DOCUMENT_APPROVAL
}