# LOCAL DEVELOPMENT
spring.datasource.url=jdbc:postgresql://localhost:5432/easyerpshop
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.redis.host=localhost
spring.redis.port=6379

spring.kafka.bootstrap-servers=localhost:9092

jwt.secret=MySuperSecretKeyThatIsAtLeast32CharactersLong

init.datasource.url=jdbc:postgresql://localhost:5432/postgres
init.datasource.username=postgres
init.datasource.password=12345678

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sunilkumar1662576@gmail.com
spring.mail.password=wrwvckepwdfvkdgt

razorpay.key=rzp_test_GGpz766jcBRnsR
razorpay.secret=jCQGUnGw7RSvy3aVEsmFuah6
razorpay.webhook-secret=secret_for_webhook_validation

storage.local.base-path=./uploads
storage.local.public-url-prefix=http://localhost:9090

storage.s3.enabled=false
storage.azure.enabled=false
storage.gcs.enabled=false

spring.jpa.show-sql=true
logging.level.com.easyerpshop=DEBUG